exports.up = function(knex, Promise) {
  return knex.schema.createTable('items', function (t) {
    t.increments()

    t.string('name').notNullable()
    t.integer('serving_size').notNullable()
    t.integer('calories').notNullable()
    t.integer('calories_from_fat')
    t.integer('protein').notNullable()
    t.integer('total_fat').notNullable()
    t.integer('saturated_fat')
    t.integer('trans_fat')
    t.integer('polyunsaturated_fat')
    t.integer('monounsaturated_fat')
    t.integer('cholesterol')
    t.integer('total_carbohydrates').notNullable()
    t.integer('fiber')
    t.integer('soluble_fiber')
    t.integer('sugars')
    t.integer('other_carbohydrates')
    t.integer('vitamin_a')
    t.integer('thiamin')
    t.integer('riboflavin')
    t.integer('niacin')
    t.integer('vitamin_b6')
    t.integer('total_vitamin_b9')
    t.integer('vitamin_b12')
    t.integer('vitamin_c')
    t.integer('vitamin_d')
    t.integer('vitamin_e')
    t.integer('vitamin_k')
    t.integer('calcium')
    t.integer('copper')
    t.integer('iron')
    t.integer('magnesium')
    t.integer('magnanese')
    t.integer('phosphorus')
    t.integer('potassium')
    t.integer('sodium')
    t.integer('zinc')
  })
}

exports.down = function(knex, Promise) {
  return knex.schema.dropTable('items')
}
